version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 manage:app
    ports:
      - 5000:5000
    env_file:
      - ./.env.prod
    depends_on:
      - db
    mem_limit: 2G
    mem_reservation: 512M
    cpus: 1.0
    storage_opt:
      size: '10G'
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod.db
  redis:
    image: "redis:alpine"

volumes:
  postgres_data_prod: